#!/usr/bin/env bash


import sys

def factorize(number):
    for i in range(2, number):
        if number % i == 0:
            return i, number // i
    return None, None

def main(filename):
    try:
        with open(filename, 'r') as file:
            numbers = [int(line.strip()) for line in file.readlines()]
            
            for number in numbers:
                p, q = factorize(number)
                print(f"{number}={p}*{q}")

    except FileNotFoundError:
        print(f"File '{filename}' not found.")
    except ValueError:
        print("Invalid input in the file. Please make sure all lines contain natural numbers greater than 1.")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
    else:
        main(sys.argv[1])
